CREATE TABLE comment (
  id BIGINT NOT NULL, 
  text VARCHAR(255), 
  post_id BIGINT, 
  user_id BIGINT, 
  PRIMARY KEY (id)
);
 CREATE TABLE post (
  post_id BIGINT NOT NULL, 
  created_date TIMESTAMP, 
  post_description VARCHAR(255), 
  post_name VARCHAR(255), 
  url VARCHAR(255), 
  vote_count INTEGER, 
  subreddit_id BIGINT, 
  user_id BIGINT, 
  PRIMARY KEY (post_id)
); 

  CREATE TABLE subreddit (
  id BIGINT NOT NULL, 
  description VARCHAR(255), 
  NAME VARCHAR(255), 
  user_user_id BIGINT, 
  PRIMARY KEY (id)
); 

  CREATE TABLE subreddit_posts (
  subreddit_id BIGINT NOT NULL, posts_post_id BIGINT NOT NULL
); 

  CREATE TABLE USER (
  user_id BIGINT NOT NULL, 
  created TIMESTAMP, 
  email VARCHAR(255), 
  is_active BOOLEAN NOT NULL, 
  password VARCHAR(255), 
  user_name VARCHAR(255), 
  PRIMARY KEY (user_id)
);
CREATE TABLE vote (
  vote_id BIGINT NOT NULL, 
  vote_type INTEGER, 
  post_id BIGINT, 
  user_id BIGINT, 
  PRIMARY KEY (vote_id)
);

create table token (
id bigint generated by default as identity,
 expiry_date timestamp,
 token varchar(255),
 user_user_id bigint,
 primary key (id));

ALTER TABLE 
  subreddit_posts 
DROP 
  CONSTRAINT IF EXISTS uk_ih17w4fa2em7w3u1tt8gqv2wh;
ALTER TABLE 
  subreddit_posts 
ADD 
  CONSTRAINT uk_ih17w4fa2em7w3u1tt8gqv2wh UNIQUE (posts_post_id);
CREATE sequence hibernate_sequence start WITH 1 increment BY 1;
ALTER TABLE 
  comment 
ADD 
  CONSTRAINT fks1slvnkuemjsq2kj4h3vhx7i1 FOREIGN KEY (post_id) REFERENCES post;
ALTER TABLE 
  comment 
ADD 
  CONSTRAINT fk8kcum44fvpupyw6f5baccx25c FOREIGN KEY (user_id) REFERENCES USER;
ALTER TABLE 
  post 
ADD 
  CONSTRAINT fk7dhm40vytolqggids4vc9ykvt FOREIGN KEY (subreddit_id) REFERENCES subreddit;
ALTER TABLE 
  post 
ADD 
  CONSTRAINT fk72mt33dhhs48hf9gcqrq4fxte FOREIGN KEY (user_id) REFERENCES USER;
ALTER TABLE 
  subreddit 
ADD 
  CONSTRAINT fkqye4s0ll7xwj74d7irovyhbvg FOREIGN KEY (user_user_id) REFERENCES USER;
ALTER TABLE 
  subreddit_posts 
ADD 
  CONSTRAINT fkl27wc8sin3rt45ayge7fanx10 FOREIGN KEY (posts_post_id) REFERENCES post;
ALTER TABLE 
  subreddit_posts 
ADD 
  CONSTRAINT fk1plpyiqs72shw84g90q0fes5r FOREIGN KEY (subreddit_id) REFERENCES subreddit;
ALTER TABLE 
  token 
ADD 
  CONSTRAINT fk79keudebybjlldk2o4i0nwqev FOREIGN KEY (user_user_id) REFERENCES USER;
ALTER TABLE 
  vote 
ADD 
  CONSTRAINT fkl3c067ewaw5xktl5cjvniv3e9 FOREIGN KEY (post_id) REFERENCES post;
ALTER TABLE 
  vote 
ADD 
  CONSTRAINT fkcsaksoe2iepaj8birrmithwve FOREIGN KEY (user_id) REFERENCES USER;
